CREATE DEFINER=`root`@`localhost` TRIGGER `checkmarksrange` BEFORE INSERT ON `student` FOR EACH ROW BEGIN

IF NEW.m1 NOT BETWEEN 0 AND 100 OR NEW.m2 NOT BETWEEN 0 AND 100 OR NEW.m3 NOT BETWEEN 0 AND 100 THEN
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Marks should be between 0 and 100';
END IF;
END